
--
-- Postgres SQL Schema dump automatic generated by geni
--


-- EXTENSIONS 

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

-- TABLES 

CREATE TABLE schema_migrations (
 id character varying (255) NOT NULL
);

-- CONSTRAINTS 

ALTER TABLE schema_migrations ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (id);

-- INDEXES 

CREATE UNIQUE INDEX schema_migrations_pkey ON public.schema_migrations USING btree (id)

