services:
  database:
    image: postgres:17.3
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/pg_hba.conf
    command: [ '-c', 'hba_file=/etc/pg_hba.conf' ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    cpu_count: 2
    networks:
      slot-system-network:
        ipv4_address: 10.5.0.2

  migrations:
    image: ghcr.io/emilpriver/geni:v1.1.5
    container_name: migrations
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres
    volumes:
      - ../../migrations:/migrations
    command: up
    networks:
      slot-system-network:
        ipv4_address: 10.5.0.3
    depends_on:
      database:
        condition: service_healthy

  slot:
    image: localhost/charlieroth/slot:0.0.1
    pull_policy: never
    container_name: slot
    restart: unless-stopped
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/liveness || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 2s
    cpu_count: 2
    environment:
      - GOGC=off
      - GOMEMLIMIT
      - GOMAXPROCS=2
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres
      - DB_MIN_CONNS=10
      - DB_MAX_CONNS=100
    expose:
      - "3000:3000"
    networks:
      slot-system-network:
        ipv4_address: 10.5.0.5
    depends_on:
      database:
        condition: service_healthy

volumes:
  database: {}

networks:
  slot-system-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24